version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
    environment:
      - 'ALLOW_ANONYMOUS_LOGIN=yes'
      - 'ZOOKEEPER_CLIENT_PORT=2181'
      - 'ZOOKEEPER_TICK_TIME=2000'
  kafka1:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka1'
    hostname: 'kafka1'
    depends_on:
      - zookeeper
    ports:
      - '9092'
      - '29092:29092'
    environment:
      - 'KAFKA_BROKER_ID=1'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'ALLOW_PLAINTEXT_LISTENER=yes'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      - 'KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost:29092'
      - 'KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:29092'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
      - 'KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0'
  kafka2:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka2'
    hostname: 'kafka2'
    depends_on:
      - zookeeper
    ports:
      - '9092'
      - '29093:29093'
    environment:
      - 'KAFKA_BROKER_ID=2'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'ALLOW_PLAINTEXT_LISTENER=yes'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      - 'KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost:29093'
      - 'KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:29093'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
      - 'KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0'
  kafka3:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka3'
    hostname: 'kafka3'
    depends_on:
      - zookeeper
    ports:
      - '9092'
      - '29094:29094'
    environment:
      - 'KAFKA_BROKER_ID=3'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'ALLOW_PLAINTEXT_LISTENER=yes'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      - 'KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://localhost:29094'
      - 'KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:29094'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE'
      - 'KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1'
      - 'KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0'
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: 'kafka-manager'
    ports:
      - '9000:9000'
    environment:
      - 'ZK_HOSTS=zookeeper:2181'

